### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by coded-witch** [coded-witch/cp#1]
`#define imps implementations`

- [ ] update topic_list
- [ ] add documentation for both [treap](https://github.com/coded-witch/cp/tree/main/library/data-structures/treap) and [treap pool](https://github.com/coded-witch/cp/tree/main/library/data-structures/treap-pool)
- [ ] clean up NT imps
- [ ] clean up Geometry imps
- [ ] clean up String imps
- [ ] start adding Graph imps for once (but clean up both Flow imps first)
